### ISSUE TITLE
Add sample Travis file

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/pod-template#12]
Although Travis is a proprietary system is the most widespread option for CI in the OSS world. Adding a sample file, ready to be tuned could be very handy for newcomers.

A sample file could be:

``` yaml
# .travis.yml

language: objective-c
before_install:
    - brew update
    - brew install xctool
install: cd Project; pod install
script: xctool -workspace Project/NAME.xcworkspace -scheme Demo test
```

We could debate whether we should recommend the usage of the xctool.
